#!/bin/bash
# scripts/lib/generate-plugin-overlay.sh -- Per-launch plugin RO overlay.
#
# Reads plugins.stagingCopies from scaffold.config.json for the active project
# and writes a docker-compose overlay file that mounts each plugin source
# read-only at /plugins-ro/<basename>. The container's _symlink_plugins
# (see container/lib/workspace-setup.sh) symlinks each one into
# /workspace/Plugins/<basename> on startup, so reviewers can read plugin
# source and the engineer can compile against it.
#
# Source this file; do not execute it directly.

[[ -n "${_LIB_GENERATE_PLUGIN_OVERLAY_LOADED:-}" ]] && return 0
readonly _LIB_GENERATE_PLUGIN_OVERLAY_LOADED=1

# _generate_plugin_overlay <script_dir> <project_id> <output_path>
#   Writes an overlay to <output_path>. Returns 0 if the file was written
#   (caller should add it to the compose -f list). Returns 1 if no plugin
#   entries are configured (caller should skip the overlay; any stale file
#   at <output_path> is removed).
#
#   Exits with error if a configured source path does not exist on disk.
#   Silent skip would let agents review code against a plugin they can't see,
#   which is exactly the bug this overlay fixes.
_generate_plugin_overlay() {
  local script_dir="$1"
  local project_id="$2"
  local out_path="$3"
  local cfg="$script_dir/scaffold.config.json"

  if [[ ! -f "$cfg" ]]; then
    rm -f "$out_path"
    return 1
  fi

  # Pull entries as <source>\x01<basename>, one per line. SOH (0x01) is the
  # delimiter because @tsv escapes backslashes (mangles Windows paths) and SOH
  # cannot appear in any filesystem path. The relativeDest basename is the
  # mount name; any "Plugins/" prefix is discarded because the container's
  # _symlink_plugins already places links under /workspace/Plugins.
  local entries
  entries=$(jq -r --arg id "$project_id" '
    (if (.projects[$id]?.plugins.stagingCopies // null) != null then .projects[$id].plugins.stagingCopies
     elif $id == "default" then (.plugins.stagingCopies // [])
     else [] end)
    | map(select(.source != null and .source != "" and .relativeDest != null and .relativeDest != ""))
    | .[]
    | "\(.source)\(.relativeDest | split("/") | last)"
  ' "$cfg")

  if [[ -z "$entries" ]]; then
    rm -f "$out_path"
    return 1
  fi

  local -a vol_lines=()
  local src name
  while IFS=$'\x01' read -r src name; do
    # jq emits CRLF on Git Bash; strip trailing CR from the last field.
    name="${name%$'\r'}"
    [[ -z "$src" ]] && continue

    if [[ ! -d "$src" ]]; then
      echo "Error: plugin source not found on disk: $src" >&2
      echo "  (configured in plugins.stagingCopies for project '$project_id', basename '$name')" >&2
      echo "  Fix the source path in scaffold.config.json or remove the entry." >&2
      exit 1
    fi

    if [[ "$src" == *"'"* ]]; then
      echo "Error: plugin source path contains a single quote; overlay generator cannot safely emit it: $src" >&2
      exit 1
    fi

    if [[ -z "$name" || "$name" == "." || "$name" == ".." || "$name" == *"/"* || "$name" == *"\\"* ]]; then
      echo "Error: plugin relativeDest basename '$name' is unsafe (must be a plain directory name)" >&2
      exit 1
    fi

    vol_lines+=("      - '${src}:/plugins-ro/${name}:ro'")
  done <<< "$entries"

  if [[ ${#vol_lines[@]} -eq 0 ]]; then
    rm -f "$out_path"
    return 1
  fi

  {
    echo "# Auto-generated by launch.sh via scripts/lib/generate-plugin-overlay.sh."
    echo "# Mounts plugins.stagingCopies entries read-only at /plugins-ro/<name>;"
    echo "# container/lib/workspace-setup.sh symlinks each into /workspace/Plugins/."
    echo ""
    echo "services:"
    echo "  claude-worker:"
    echo "    volumes:"
    local line
    for line in "${vol_lines[@]}"; do
      echo "$line"
    done
  } > "$out_path"

  return 0
}
